version: '3.8'

services:
  vexa-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: vexa-app-dev
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_SITE_URL=http://localhost:3000
      - NEXT_PUBLIC_GA_MEASUREMENT_ID=G-DEVELOPMENT
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: pnpm dev
    networks:
      - vexa-network-dev

networks:
  vexa-network-dev:
    driver: bridge 