version: '3.8'

services:
  vexa-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vexa-app
    restart: unless-stopped
    command: pnpm start
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    # Use a healthcheck that's more lenient
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 0
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - vexa-network

networks:
  vexa-network:
    driver: bridge 